# group_vars/all/postgres.yml

postgresql_users:
  - name: demo
    password: '{{ secrets_demo_password }}'
    state: present

postgresql_databases:
  - name: demo
    owner: demo
    encoding: UTF-8
    state: present
