# roles/local.adminer/defaults/main.yml

adminer_install_path: /opt/adminer
adminer_version: 5.4.2
adminer_download_url:
  https://github.com/vrana/adminer/releases/download/v{{ adminer_version }}/adminer-{{ adminer_version }}.php
