# roles/local.adminer/tasks/main.yml

- name: Ensure adminer directory exists
  file:
    path: '{{ adminer_install_path }}'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download Adminer
  get_url:
    url: '{{ adminer_download_url }}'
    dest: '{{ adminer_install_path }}/adminer.php'
